### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by 2734359061** [Woodenonez/DyObAv_MPCnWTA_Warehouse#3]
Hello, I am encountering the "ModuleNotFoundError: No module named 'util'" issue when running your main_ros.py file. The original code includes "from util import mapnet" and "from util import basic_agent", but there is no util.py file.

**Comment by Woodenonez** [comment]
Hi,

Thank you for your interest. Unfortunately, we have abandoned the ROS Neotic implementation and migrated to ROS2! So, after several updates, the original main_ros.py doesn't work now. We also abandoned the ROS interface in this project and are now using pure ROS packages.

If you want to have a try, `mapnet` is now `basic_map/[Dep] graph_scene.py`, and `basic_agent` is now in `src` as a single module. You might be able to make it work after making these modifications, but we are focusing on our new work and will not support the ROS part in this repo. **However**, we can still help you with any questions on the Python implementation or the paper.

Since the new work is under development, we cannot release the new ROS2 code now, but hopefully, we can release it by the end of this year. Once the new code is released, this repo will be archived and a link to the new work will be added in README.

Hope you find this useful. Cheers!

**Comment by 2734359061** [comment]
Hello,

Thank you so much for your prompt response and detailed explanation. I'm genuinely interested in your research. I was able to locate the two files you mentioned. However, I noticed that the basic_agent.py file in the src folder has undergone significant updates. The content now only includes the MovingAgent module, and the basic_agent module appears to be entirely different. For instance, in the main_ros.py file, there is a line of code: the_planner = basic_agent.Planner(scene_graph.NG), but the MovingAgent module doesn’t have a Planner class. It seems like a lot has changed in the code.

Could you please advise on how to resolve this issue? It looks like the "Planner" is a crucial part of the path planning code. Could you let me know where this function is located in the updated version? If possible, it would be immensely helpful if you could share the original code (before the updates) that was associated with the paper.

Thank you again for your time and assistance. I really appreciate it.

Best regards,
Hong





草帽小子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Woodenonez/DyObAv_MPCnWTA_Warehouse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月31日(星期六) 凌晨3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Woodenonez/DyObAv_MPCnWTA_Warehouse] ModuleNotFoundError: No module named 'util' (Issue #3)





 
Hi,
 
Thank you for your interest. Unfortunately, we have abandoned the ROS Neotic implementation and migrated to ROS2! So, after several updates, the original main_ros.py doesn't work now. We also abandoned the ROS interface in this project and are now using pure ROS packages.
 
If you want to have a try, mapnet is now basic_map/[Dep] graph_scene.py, and basic_agent is now in src as a single module. You might be able to make it work after making these modifications, but we are focusing on our new work and will not support the ROS part in this repo. However, we can still help you with any questions on the Python implementation or the paper.
 
Since the new work is under development, we cannot release the new ROS2 code now, but hopefully, we can release it by the end of this year. Once the new code is released, this repo will be archived and a link to the new work will be added in README.
 
Hope you find this useful. Cheers!

**Comment by Woodenonez** [comment]
I'll take a look later and try to modify the main_ros module. Will let you know :)

**Comment by 2734359061** [comment]
> I'll take a look later and try to modify the main_ros module. Will let you know :)

I hope you’re doing well. I just wanted to follow up on our previous conversation regarding the modifications to the main_ros module. It's been a few days, and I was wondering if you had a chance to take a look at it.
I really appreciate your help and am looking forward to any updates you might have.

**Comment by Woodenonez** [comment]
Hi I haven't forgot about it. Don't worry.
Unfortunately, I'm in business trip recently and should have time next week. I'll get back to you.

**Comment by Woodenonez** [comment]
Hi @2734359061 

I happened to have time for a quick view.
Now, there is a new branch called `ros_version`. This is the old code when we tested the ROS simulation.
It should work still, but I cannot offer you any help with the ROS part since it was implemented by a former colleague.

Hope this helps!

BR//Z

**Comment by 2734359061** [comment]
<img width="650" alt="1" src="https://github.com/user-attachments/assets/83361117-fe9f-40df-8a7f-1ecd978a3ac1">
Thank you so much for your help. I tried using the new code you uploaded and made some adjustments to the module references, as shown in the attached image. However, there are still a few modules that cannot be found. Could this also be due to the recent code updates?

**Comment by Woodenonez** [comment]
Did you completely switch to the ros branch: [ros_version](https://github.com/Woodenonez/DyObAv-MPCnWTA-Warehouse/tree/ros_version)? If you do, you should be able to see all the modules. For example, the [src/util/basic_objclass](https://github.com/Woodenonez/DyObAv-MPCnWTA-Warehouse/blob/ros_version/src/util/basic_objclass.py) module.

**Comment by 2734359061** [comment]
I hope this message finds you well. First, I would like to sincerely apologize for my delayed response as I have been occupied with other matters recently. I truly appreciate the work you’ve done on the newly added ros_version branch, as it has resolved several of the issues I was facing.

However, I encountered a problem while running the ros_version code due to the absence of the solver. I attempted to generate the solver by using the solver_build.py script from the main branch along with the configuration files from ros_version. Unfortunately, this led to some dimensionality issues during the solver generation process.

Could you kindly confirm if there is a dedicated solver generation file specifically for the ros_version branch? If so, I would greatly appreciate any guidance or instructions on how to properly generate the solver for this version.

Thank you very much for your time and support. I look forward to your response and truly appreciate your assistance in this matter.

**Comment by Woodenonez** [comment]
Hi,
This is related to the version of matplotlib. The ros branch uses an old version where you don't need to specify the key for "angle" input but now you need to. Anyway, I fixed this issue by addressing the key, and I also tested the main file which ran successfully.
BTW you can use "test_block_mpc.py" to generate the solver as well, and I added this instruction in the readme of the ros branch.

**Comment by 2734359061** [comment]
Thank you very much for your help, now finally can run ros simulation, although the effect of running out is not very good at present, but at least it can run

**Comment by Woodenonez** [comment]
That's good to know. We didn't have time to fine-tune the ROS part due to a limited time. And I think you probably need to set a lower simulation frequency in Gazebo. Now I have developed a new ROS2 simulation and will update it in this repo's readme later. After the new repo is ready, this repo will be achieved.
